### ISSUE TITLE
wrong device

### ISSUE THREAD

**Issue by mote166** [drew-pm-plugins/DeviceNametag#3]
some players get wrong device name and sometimes i get that, it happens randomly

**Comment by Wumpotamus** [comment]
@mote166 Sorry for the late response (github doesn't email me), what devices do you get this with?

**Comment by mote166** [comment]
no specific device and no specific time it happens randomly like 3 out of 10 times it shows wrong device info

**Comment by Wumpotamus** [comment]
@mote166 I'll look into it, thanks for reporting.

**Comment by Wumpotamus** [comment]
Try with the latest update, I don't think it fixed it, the ids are probably outdated, but when you do test it, tell me what device it gives you and what device you're on.

**Comment by mote166** [comment]
it still gave wrong info about an ios (iphone 6s plus) being labeled as an android and after they re joined it went back to be ios, sorry for the late reply .

**Comment by Wumpotamus** [comment]
It's okay, have you tried resetting the config?

**Comment by mote166** [comment]
i did

**Comment by Wumpotamus** [comment]
Try removing all plugins except this and try again, I've had someone test it and they've had no issues

**Comment by mote166** [comment]
this is not possible cuz my server is a public server and it only happens randomly so it would take alot of time to get it to happen, its ok its not that big problem since it happens randomly and not alot. u can close this issue if u want.
